spring:
  datasource:
    username: root
    password: 414670_Lzj
    url: jdbc:mysql://bj-cynosdbmysql-grp-fp44mvsq.sql.tencentcdb.com:25373/flight?serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    # template engine
    thymeleaf:
      mode: HTML5
      encoding: utf-8
      # disable cache
      cache: false

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    # Turn on the hump naming conversion
    map-underscore-to-camel-case: true

server:
  port: 8080
